### ISSUE TITLE
Support DRAAdminAccess and DRAResourceClaimDeviceStatus featuregate during initialization

### ISSUE THREAD

**Issue by googs1025** [kubernetes-sigs/dra-example-driver#76]
in v1.32 version, we have `DRAAdminAccess` and `DRAResourceClaimDeviceStatu` featuregate
do we need to support DRAAdminAccess and DRAResourceClaimDeviceStatus featuregate during initializing cluster.

https://github.com/kubernetes-sigs/dra-example-driver/blob/cfe7e11dce2a87be0985fd2ea242b3676d5c7bb1/demo/scripts/kind-cluster-config.yaml#L11-L29

```yaml
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          runtime-config: "resource.k8s.io/v1beta1=true"
          feature-gates: "DRAAdminAccess=true,DRAResourceClaimDeviceStatus=true"
    scheduler:
        extraArgs:
          v: "1"
          feature-gates: "DRAAdminAccess=true,DRAResourceClaimDeviceStatus=true"
    controllerManager:
        extraArgs:
          v: "1"
          feature-gates: "DRAAdminAccess=true,DRAResourceClaimDeviceStatus=true"

```
